create table if not exists public.pro_player_access (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  player_user_id uuid not null references public.user_profiles(id) on delete cascade,
  pro_user_id uuid not null references public.user_profiles(id) on delete cascade,
  constraint pro_player_access_unique unique (player_user_id, pro_user_id),
  constraint pro_player_access_not_self check (player_user_id <> pro_user_id)
);

create index if not exists pro_player_access_player_idx
  on public.pro_player_access (player_user_id);

create index if not exists pro_player_access_pro_idx
  on public.pro_player_access (pro_user_id);

create table if not exists public.pro_account_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references public.user_profiles(id) on delete cascade,
  email text not null,
  user_name text,
  status text not null default 'pending',
  reviewed_at timestamptz,
  reviewed_by uuid references public.user_profiles(id) on delete set null,
  constraint pro_account_requests_unique_user unique (user_id),
  constraint pro_account_requests_status_check
    check (status in ('pending', 'approved', 'rejected'))
);

create index if not exists pro_account_requests_status_idx
  on public.pro_account_requests (status, created_at);

alter table public.pro_player_access enable row level security;
alter table public.pro_account_requests enable row level security;

drop policy if exists "Players can view their pro access rows" on public.pro_player_access;
create policy "Players can view their pro access rows"
on public.pro_player_access
for select
to authenticated
using (
  auth.uid() = player_user_id
  or auth.uid() = pro_user_id
);

drop policy if exists "Players can insert their pro access rows" on public.pro_player_access;
create policy "Players can insert their pro access rows"
on public.pro_player_access
for insert
to authenticated
with check (auth.uid() = player_user_id);

drop policy if exists "Players can delete their pro access rows" on public.pro_player_access;
create policy "Players can delete their pro access rows"
on public.pro_player_access
for delete
to authenticated
using (auth.uid() = player_user_id);

drop policy if exists "Users can create their own pro account request" on public.pro_account_requests;
create policy "Users can create their own pro account request"
on public.pro_account_requests
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can view their own pro account request" on public.pro_account_requests;
create policy "Users can view their own pro account request"
on public.pro_account_requests
for select
to authenticated
using (
  auth.uid() = user_id
  or exists (
    select 1
    from public.user_profiles up
    where up.id = auth.uid()
      and up.role = 'admin'
  )
);

drop policy if exists "Users can update their pending pro account request" on public.pro_account_requests;
create policy "Users can update their pending pro account request"
on public.pro_account_requests
for update
to authenticated
using (auth.uid() = user_id and status = 'pending')
with check (auth.uid() = user_id and status = 'pending');

create or replace function public.enforce_max_two_pros()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if (
    select count(*)
    from public.pro_player_access ppa
    where ppa.player_user_id = new.player_user_id
  ) >= 2 then
    raise exception 'You can only allow up to 2 pros.';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_max_two_pros_trigger on public.pro_player_access;
create trigger enforce_max_two_pros_trigger
before insert on public.pro_player_access
for each row
execute function public.enforce_max_two_pros();

create or replace function public.can_view_player_data(p_target_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    case
      when auth.uid() is null or p_target_user_id is null then false
      when auth.uid() = p_target_user_id then true
      when exists (
        select 1
        from public.user_profiles up
        where up.id = auth.uid()
          and up.role = 'admin'
      ) then true
      when exists (
        select 1
        from public.pro_player_access ppa
        join public.user_profiles up on up.id = auth.uid()
        where ppa.player_user_id = p_target_user_id
          and ppa.pro_user_id = auth.uid()
          and up.role = 'pro'
      ) then true
      else false
    end;
$$;

grant execute on function public.can_view_player_data(uuid) to authenticated;

create or replace function public.get_available_pros()
returns table (
  id uuid,
  email text,
  user_name text
)
language sql
security definer
set search_path = public
as $$
  select up.id, up.email, up.user_name
  from public.user_profiles up
  where up.role = 'pro'
  order by coalesce(up.user_name, up.email), up.id;
$$;

grant execute on function public.get_available_pros() to authenticated;

create or replace function public.get_my_pro_access()
returns table (
  pro_user_id uuid
)
language sql
security definer
set search_path = public
as $$
  select ppa.pro_user_id
  from public.pro_player_access ppa
  where ppa.player_user_id = auth.uid()
  order by ppa.created_at, ppa.id;
$$;

grant execute on function public.get_my_pro_access() to authenticated;

create or replace function public.get_players_for_pro()
returns table (
  id uuid,
  email text,
  user_name text
)
language sql
security definer
set search_path = public
as $$
  select up.id, up.email, up.user_name
  from public.pro_player_access ppa
  join public.user_profiles up on up.id = ppa.player_user_id
  where ppa.pro_user_id = auth.uid()
  order by coalesce(up.user_name, up.email), up.id;
$$;

grant execute on function public.get_players_for_pro() to authenticated;

create or replace function public.grant_pro_access(p_pro_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_user_id uuid;
begin
  v_player_user_id := auth.uid();

  if v_player_user_id is null then
    raise exception 'You must be signed in to grant pro access.';
  end if;

  if not exists (
    select 1
    from public.user_profiles up
    where up.id = p_pro_user_id
      and up.role = 'pro'
  ) then
    raise exception 'Selected user is not a pro.';
  end if;

  insert into public.pro_player_access (player_user_id, pro_user_id)
  values (v_player_user_id, p_pro_user_id)
  on conflict (player_user_id, pro_user_id) do nothing;
end;
$$;

grant execute on function public.grant_pro_access(uuid) to authenticated;

create or replace function public.revoke_pro_access(p_pro_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'You must be signed in to revoke pro access.';
  end if;

  delete from public.pro_player_access
  where player_user_id = auth.uid()
    and pro_user_id = p_pro_user_id;
end;
$$;

grant execute on function public.revoke_pro_access(uuid) to authenticated;

create or replace function public.get_recent_sg_stats_for_user(
  p_target_user_id uuid,
  p_shot_group text,
  p_round_limit integer default 10
)
returns table (
  distance_range text,
  shots_in_group bigint,
  avg_sg_value numeric,
  fairways_hit bigint,
  fairway_hit_percentage numeric
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.can_view_player_data(p_target_user_id) then
    raise exception 'You do not have access to this player''s statistics.';
  end if;

  return query
  with recent_rounds as (
    select r.id
    from public.rounds r
    where r.user_id = p_target_user_id
      and r.is_finalised = true
    order by r.round_date desc nulls last, r.id desc
    limit greatest(coalesce(p_round_limit, 10), 0)
  ),
  recent_shots as (
    select
      s.distance_to_pin,
      s.sg_value,
      s.lie_type,
      lead(s.lie_type) over (
        partition by s.round_hole_id
        order by s.shot_number
      ) as next_lie_type
    from public.shots s
    join public.round_holes rh on s.round_hole_id = rh.id
    join recent_rounds rr on rr.id = rh.round_id
    where s.sg_value is not null
      and s.distance_to_pin is not null
  )
  select
    case
      when lower(trim(p_shot_group)) = 'putting' then
        case
          when s.distance_to_pin >= 0 and s.distance_to_pin < 4 then '0 to 3'
          when s.distance_to_pin >= 4 and s.distance_to_pin < 8 then '4 to 7'
          when s.distance_to_pin >= 8 and s.distance_to_pin < 12 then '8 to 11'
          when s.distance_to_pin >= 12 and s.distance_to_pin < 16 then '12 to 15'
          when s.distance_to_pin >= 16 and s.distance_to_pin < 21 then '16 to 20'
          when s.distance_to_pin >= 21 and s.distance_to_pin < 31 then '21 to 30'
          when s.distance_to_pin >= 31 and s.distance_to_pin < 41 then '31 to 40'
          when s.distance_to_pin >= 41 and s.distance_to_pin < 51 then '41 to 50'
          when s.distance_to_pin >= 51 and s.distance_to_pin < 61 then '51 to 60'
          when s.distance_to_pin >= 61 and s.distance_to_pin < 75 then '61 to 74'
          when s.distance_to_pin >= 75 and s.distance_to_pin < 120 then '75 to 119'
          else '120+'
        end
      when lower(trim(p_shot_group)) = 'driving' then
        'Driving'
      when lower(trim(p_shot_group)) = 'chipping' then
        case
          when s.distance_to_pin >= 0 and s.distance_to_pin <= 10 then '1 to 10'
          when s.distance_to_pin >= 11 and s.distance_to_pin <= 20 then '11 to 20'
          when s.distance_to_pin >= 21 and s.distance_to_pin <= 30 then '21 to 30'
          else '31+'
        end
      else
        case
          when s.distance_to_pin >= 31 and s.distance_to_pin <= 60 then '31 to 60'
          when s.distance_to_pin >= 61 and s.distance_to_pin <= 90 then '61 to 90'
          when s.distance_to_pin >= 91 and s.distance_to_pin <= 120 then '91 to 120'
          when s.distance_to_pin >= 121 and s.distance_to_pin <= 150 then '121 to 150'
          when s.distance_to_pin >= 151 and s.distance_to_pin <= 200 then '151 to 200'
          else '201+'
        end
    end as distance_range,
    count(*) as shots_in_group,
    round(avg(s.sg_value), 3) as avg_sg_value,
    case
      when lower(trim(p_shot_group)) = 'driving' then
        count(*) filter (
          where lower(trim(coalesce(s.next_lie_type, ''))) = 'fairway'
        )
      else null
    end as fairways_hit,
    case
      when lower(trim(p_shot_group)) = 'driving' then
        round(
          (
            count(*) filter (
              where lower(trim(coalesce(s.next_lie_type, ''))) = 'fairway'
            )::numeric
            / nullif(count(*), 0)
          ) * 100,
          1
        )
      else null
    end as fairway_hit_percentage
  from recent_shots s
  where (
      (lower(trim(p_shot_group)) = 'putting' and lower(trim(s.lie_type)) = 'green')
      or
      (lower(trim(p_shot_group)) = 'driving' and lower(trim(s.lie_type)) = 'tee')
      or
      (
        lower(trim(p_shot_group)) = 'chipping'
        and lower(trim(s.lie_type)) not in ('green', 'tee')
        and s.distance_to_pin >= 0
        and s.distance_to_pin <= 30
      )
      or
      (
        lower(trim(p_shot_group)) = 'approach'
        and lower(trim(s.lie_type)) not in ('green', 'tee')
        and s.distance_to_pin > 30
      )
    )
  group by 1
  order by min(s.distance_to_pin);
end;
$$;

grant execute on function public.get_recent_sg_stats_for_user(uuid, text, integer) to authenticated;

create or replace function public.get_round_summary_list(
  p_user_id uuid,
  p_limit integer,
  p_offset integer,
  p_recent_limit integer default 30
)
returns table (
  id bigint,
  played_date date,
  course text,
  tee text,
  finished boolean,
  part_finalised boolean,
  holes_played integer,
  score bigint,
  sg_total numeric
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.can_view_player_data(p_user_id) then
    raise exception 'You do not have access to this player''s rounds.';
  end if;

  return query
  with ordered_rounds as (
    select
      r.id,
      r.round_date,
      r.is_finalised,
      coalesce(r.part_finalised, false) as part_finalised,
      c.name as course_name,
      t.color as tee_color
    from public.rounds r
    left join public.courses c on c.id = r.course_id
    left join public.tees t on t.id = r.tee_id
    where r.user_id = p_user_id
    order by r.round_date desc nulls last, r.id desc
  ),
  user_rounds as (
    select *
    from ordered_rounds
    limit greatest(coalesce(p_recent_limit, 30), 0)
    offset 0
  ),
  paged_rounds as (
    select *
    from user_rounds
    limit greatest(coalesce(p_limit, 0), 0)
    offset greatest(coalesce(p_offset, 0), 0)
  ),
  round_scores as (
    select
      rh.round_id,
      sum(case when coalesce(rh.completed, false) then rh.score else 0 end) as total_score,
      count(*) filter (where coalesce(rh.completed, false))::integer as holes_played
    from public.round_holes rh
    join paged_rounds ur on ur.id = rh.round_id
    group by rh.round_id
  ),
  round_sg as (
    select
      rh.round_id,
      round(sum(s.sg_value)::numeric, 3) as total_sg
    from public.round_holes rh
    join paged_rounds ur on ur.id = rh.round_id
    join public.shots s on s.round_hole_id = rh.id
    where s.sg_value is not null
    group by rh.round_id
  )
  select
    ur.id,
    ur.round_date as played_date,
    coalesce(ur.course_name, 'Unknown course') as course,
    coalesce(ur.tee_color, 'Unknown tee') as tee,
    coalesce(ur.is_finalised, false) as finished,
    coalesce(ur.part_finalised, false) as part_finalised,
    coalesce(rs.holes_played, 0) as holes_played,
    rs.total_score as score,
    rsg.total_sg as sg_total
  from paged_rounds ur
  left join round_scores rs on rs.round_id = ur.id
  left join round_sg rsg on rsg.round_id = ur.id
  order by ur.round_date desc nulls last, ur.id desc;
end;
$$;

grant execute on function public.get_round_summary_list(uuid, integer, integer, integer) to authenticated;

create or replace function public.get_round_shots_for_view(p_round_id bigint)
returns table (
  course_name text,
  part_finalised boolean,
  round_date date,
  tee_color text,
  shot_id bigint,
  hole_number integer,
  round_hole_id bigint,
  shot_number integer,
  distance_to_pin numeric,
  lie_type text,
  penalty_strokes integer,
  recovery boolean,
  holed_out boolean,
  score integer,
  sg_value numeric
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.rounds r
    where r.id = p_round_id
  ) then
    raise exception 'Round not found.';
  end if;

  if not exists (
    select 1
    from public.rounds r
    where r.id = p_round_id
      and public.can_view_player_data(r.user_id)
  ) then
    raise exception 'You do not have access to this round.';
  end if;

  return query
  select
    coalesce(c.name, 'Unknown course') as course_name,
    coalesce(r.part_finalised, false) as part_finalised,
    r.round_date,
    coalesce(t.color, 'Unknown tee') as tee_color,
    s.id as shot_id,
    h.hole_number::integer,
    rh.id as round_hole_id,
    s.shot_number::integer,
    s.distance_to_pin,
    s.lie_type,
    coalesce(s.penalty_strokes, 0)::integer as penalty_strokes,
    coalesce(s.recovery, false) as recovery,
    coalesce(s.holed_out, false) as holed_out,
    rh.score::integer,
    s.sg_value
  from public.rounds r
  left join public.courses c on c.id = r.course_id
  left join public.tees t on t.id = r.tee_id
  join public.round_holes rh on rh.round_id = r.id
  join public.holes h on h.id = rh.hole_id
  left join public.shots s on s.round_hole_id = rh.id
  where r.id = p_round_id
  order by h.hole_number, s.shot_number nulls last;
end;
$$;

grant execute on function public.get_round_shots_for_view(bigint) to authenticated;
